<a href="https://colab.research.google.com/github/arthy271-ctrl/python/blob/main/first.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [89]:
import numpy as np
a  = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[1 2 3 4]
 [5 6 7 8]]


In [90]:
#to get shape (row,col)
a.shape

(2, 7)

In [91]:
#to get the dimension of array
a.ndim

b.ndim

2

In [92]:
print(a[1,:])    #to get 2nd row of mat a
print(a[0,:])    #to get 1rst row of mat a
print(a[:,0])    #to get all rows 1rst col of mat a
print(a[:,5])    #to get all rows 6th col of mat a






[ 8  9 10 11 12 13 14]
[1 2 3 4 5 6 7]
[1 8]
[ 6 13]


In [93]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [94]:
# to access elements of a 3 dimension array

print(c[0,1,])
print(c[1,:])
print(c[:,1,:])

[3 4]
[[5 6]
 [7 8]]
[[3 4]
 [7 8]]


In [95]:
#to replace elements of a 3 dimensional array

c[1,0,1]=0
print(c)


[[[1 2]
  [3 4]]

 [[5 0]
  [7 8]]]


In [96]:
#to repeat any array for number of times

x=np.array([[1,2,3]])   #give it in 2d so it can run in axis=1 too( [ [] ] )
arr1=np.repeat(x,3)
arr2=np.repeat(x,3, axis=0)   #axis=0: The Vertical direction (Downwards, along the Rows)
arr3=np.repeat(x,4, axis=1)   #axis=1: The Horizontal direction (Sideways, along the Columns)
print(arr1)
print(arr2)
print(arr3)

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 1 2 2 2 2 3 3 3 3]]


In [97]:
from random import random

#to generate random numbers
print(np.random.rand(4,2))

#to generate random decimal numbers from 0 to 6
print(np.random.randint(7,size=(3,3)))

#to generate random integers from -5 to 2
print(np.random.randint(-5,3,size=(3,3)))


[[0.53955161 0.87234395]
 [0.90296626 0.79549705]
 [0.19294185 0.64513936]
 [0.32271806 0.77027015]]
[[1 1 3]
 [3 2 6]
 [1 6 4]]
[[-1  2  2]
 [-5  1  1]
 [ 2 -5 -1]]


In [98]:
print(np.zeros((2,3)))     #to create zero matrix
print(np.ones((3,4)))     #to create ones matrix
print(np.identity(3))     #to create identity matrix
print(np.full((2,2),99))  #to create a 2 by2 matrix with fully by 99
print(np.full_like(a,4))  #to create a matrix like matrix-a with fully 4
print(np.full(a.shape,4))  #to create a matrix with same order as matrix-a with fully 4

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[99 99]
 [99 99]]
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


In [99]:
# qn to print an as shown in output:

output=np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
output[1:4,1:4]=z     # here row= 1 to 3,ie,1:4 (and) column= 1 to 3,ie, 1:4
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [100]:
######## COPYING OF ARRAYS--- IMPORTANT

m=np.array([1,2,3,4])
n=m
print('m=',m)
print('n=',n)
n[0]=100
print('m=',m)   #change in n AFFECTED m too
print('n=',n)



m= [1 2 3 4]
n= [1 2 3 4]
m= [100   2   3   4]
n= [100   2   3   4]


In [101]:
###### TO AVOID THAT MISTAKE FROM PREVIOUS COPYING CODE:

p=np.array([1,2,3,4])
q=p.copy()
print('p=',p)
print('q=',q)
q[0]=100
print('p=',p)     # change in q DID NOT AFFECT p
print('q=',q)


p= [1 2 3 4]
q= [1 2 3 4]
p= [1 2 3 4]
q= [100   2   3   4]


In [102]:
# Arithmetic and basic math operations

print(m+2)
print(m-2)
print(m*2)
print(m/2)
print(m**2)
print(m+p)
print(m-p)
print(np.cos(m))


[102   4   5   6]
[98  0  1  2]
[200   4   6   8]
[50.   1.   1.5  2. ]
[10000     4     9    16]
[101   4   6   8]
[99  0  0  0]
[ 0.86231887 -0.41614684 -0.9899925  -0.65364362]


In [103]:
###Linear algebra           ### [  https://docs.scipy.org/doc/numpy/reference/routines.linalg.html  ]

a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
print(np.matmul(a,b))       #to multiply matrix and simply using a*b gives error
c=np.identity(3)
print(np.linalg.det(c))     #REMEMBER, determinant can be found only for square matrices

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]
1.0


In [104]:
###Statistics

stat=np.array([[1,2,3],[4,5,6]])
print(np.max(stat))          #to get max number of matrix
print(np.max(stat,axis=0))   #to get max number along the rows,ie,downward
print(np.max(stat,axis=1))   #to get max number along the columns,ie,sideways
print(np.min(stat))          #to get min number of matrix
print(np.min(stat,axis=0))   #to get min number along the rows,ie,downward
print(np.min(stat,axis=1))   #to get min number along the columns,ie,sideways
print(np.sum(stat))          #to get sum of matrix
print(np.sum(stat,axis=0))   #to get sum of number along the rows,ie,downward
print(np.sum(stat,axis=1))   #to get sum of number along the column,ie,sideways


6
[4 5 6]
[3 6]
1
[1 2 3]
[1 4]
21
[5 7 9]
[ 6 15]


In [105]:
#Reorganising array

before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.reshape((8,1)))
print(before.reshape((4,2)))
print(before.reshape((2,2,2)))
print(before.reshape((2,3)))     #gives error as the nof elements in matrix != matrix elements of (2,3)


[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [106]:
#Vertical stacking         # no.of columns should be same

v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
print(np.vstack([v1,v2]))
print(np.vstack([v1,v2,v1,v2]))
print(np.vstack((v2,v1)))       ##both " () " or " [] " can be used

# if v1= 1 2 3 4 5 , error would be shown

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
[[5 6 7 8]
 [1 2 3 4]]


In [107]:
#Horizontal stacking       # no.of rows shouls be same

h1=np.ones((2,4))
h2=np.zeros((2,6))
print(np.hstack((h1,h2)))
print(np.hstack((h2,h1)))
print(np.hstack([h1,h2,h1]))

[[1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]]


In [108]:
# Accessing from files

# This creates 'data.txt' inside Google Colab's cloud environment

with open('data.txt', 'w') as f:
    f.write("1,2,3\n4,5,6\n7,8,9")

print("File created on Google's server!")

# Now NumPy can read it perfectly

data=np.genfromtxt('data.txt')
print(data)
data = np.genfromtxt('data.txt', delimiter=',')
print(data)
print(data.astype('int'))      # to change the type of file content while printing or at moment
print(data.astype('int16'))
print(data.astype('int32'))
data=data.astype('int')        #to change the file type as int itself
print(data)

File created on Google's server!
[nan nan nan]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [109]:
# boolean masking and advanced indexing

print(data>2)
print(data[data>2])
print(data>=3)
print(np.any(data/2,axis=0))
print(np.any(np.any(data/2,axis=1)))
print(np.all(data>4))
print(np.all(data>4,axis=0))
print(np.all(data>4,axis=1))


[[False False  True]
 [ True  True  True]
 [ True  True  True]]
[3 4 5 6 7 8 9]
[[False False  True]
 [ True  True  True]
 [ True  True  True]]
[ True  True  True]
True
False
[False False False]
[False False  True]


In [112]:
print(((data<2)&(data>5)))
print(~((data<2)&(data>5)))

[[False False False]
 [False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [116]:
a=np.array([1,2,3,4,5,6,7,8])
print(a[[1,4,6]])    ###to get desired elements from list


[2 5 7]


In [10]:
# Create a 5 × 5 matrix filled entirely with the number 100.
# Then, change only the center number to 0
import numpy as np
mat1=np.full((5,5),100)
print(mat1)
mat1[2,2]=0
print(mat1)
r1=np.random.randint(1,100,size=(5,4))
print(r1)
print(r1[r1>50])
i=np.identity(4)
print(i)
print(i.reshape(1,16))

[[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]
[[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100   0 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]
[[29 38  5 71]
 [25 44 84 43]
 [93 72  3 11]
 [80 50 37 64]
 [32 61 37 54]]
[71 84 93 72 80 64 61 54]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
